[[headers]]
  for = "/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "video/mp4"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build]
  publish = "dist"
  command = "npm run build" 